// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiwzytghqcatnsmlfnzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppd3p5dGdocWNhdG5zbWxmbnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTc0NTksImV4cCI6MjA2ODEzMzQ1OX0.52V9PW0TjPyXENy_zRpf1D8ExZrvArM9dO682l_CqWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});